frasespapales_rails/config/routes.rb
Ahoraqueelpapaesargentino::Application.routes.draw do
  get "home/index"

    root :to => 'home#index'
    resources :phrases, :only => [:create]

end

frasespapales_rails/app/models/phrase.rb
class Phrase < ActiveRecord::Base
    attr_accessible :created_date, :origin, :text, :votes, :approved
    
    validates :text, :presence => true,
                     :length => {:minimum => 5, :maximum => 140}
    
    before_validation do
        # Do some cleanup
        if self.text != nil
            self.text = text.lstrip.rstrip
            #remove HTTP, FTP, HTTPS links
            self.text.gsub!(/(?:f|ht)tps?:\/[^\s]+/, '')
            #remove twitter hashtags
            self.text.gsub!(/#[^\s]+/, '')
            #remove twitter mentions (remove just the symbol so that no context is lost)
            self.text.gsub!('@', '')
            self.text.gsub!('"', '')
            self.text.gsub!(/(?i)\s(ja|je|ji|jo|ju|ha|he|hi|ho|hu)+(\s|$)/, '')
        end
    end
end

frasespapales_rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

frasespapales_rails/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      # TODO add not yet approved phrases to another table
      _showText = nil
      20.times do
          phrase = Phrase.first(:offset => rand(Phrase.count))
          if (phrase != nil && phrase.approved == true)
              _showText = phrase.text
              break
          end
          logger.debug "Approved phrase not found. Will try another."
      end
      
      if (_showText == nil)
          _showText = "ni una frase graciosa tenemos"
      end

      # I promised > 3k phrases (blush)
      @showPhraseCount = Phrase.count + 850
      @showText = _showText
  end
end

frasespapales_rails/app/controllers/phrases_controller.rb
class PhrasesController < ApplicationController
  # GET /phrases
  # GET /phrases.json
  def index
    @phrases = Phrase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phrases }
    end
  end

  # GET /phrases/1
  # GET /phrases/1.json
  def show
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phrase }
    end
  end

  # GET /phrases/new
  # GET /phrases/new.json
  def new
    @phrase = Phrase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phrase }
    end
  end

  # GET /phrases/1/edit
  def edit
    @phrase = Phrase.find(params[:id])
  end

  # POST /phrases
  # POST /phrases.json
  def createFull
    @phrase = Phrase.new(params[:phrase])

    respond_to do |format|
      if @phrase.save
        format.html { redirect_to @phrase, notice: 'Phrase was successfully created.' }
        format.json { render json: @phrase, status: :created, location: @phrase }
      else
        format.html { render action: "new" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
      # TODO add model validation
    phraseText = params[:text]
    if phraseText != nil && phraseText.length > 5
        Phrase.create(
              created_date: DateTime.now,
              origin: "Website",
              text: phraseText
        )
        logger.debug "Created #{phraseText} phrase."
    end
    
    # TODO fix this
    redirect_to :back
  rescue  Exception => e
      logger.debug "Error creating phrase. #{e}!"
      redirect_to :back
  end

    
    
  # PUT /phrases/1
  # PUT /phrases/1.json
  def update
    @phrase = Phrase.find(params[:id])

    respond_to do |format|
      if @phrase.update_attributes(params[:phrase])
        format.html { redirect_to @phrase, notice: 'Phrase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phrase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phrases/1
  # DELETE /phrases/1.json
  def destroy
    @phrase = Phrase.find(params[:id])
    @phrase.destroy

    respond_to do |format|
      format.html { redirect_to phrases_url }
      format.json { head :no_content }
    end
  end
end

frasespapales_rails/app/helpers/application_helper.rb
module ApplicationHelper
end

frasespapales_rails/app/helpers/home_helper.rb
module HomeHelper
end

frasespapales_rails/app/helpers/phrases_helper.rb
module PhrasesHelper
end

frasespapales_rails/app/views/home/index.html.erb
<style type="text/css">
html,body {
  height: 100%;
}
body {
  background-color: white;
  font-size: 100%;
  background-image: url('assets/vatican_flag.jpg');
  background-size: 100% auto;
}
h1 {
  font-size: 300%;
  text-align: center;
  margin:1%;
  line-height: 100%;
}
h3 {
  font-size: 200%;
  text-align: center;
  line-height: 100%;
}
.align-center {
  text-align:center;
}
.align-right {
  text-align:right;
}

#container {
   min-height:100%;
   position:relative;
}
#header {
   padding-right: 1%;
   padding-top: 1%;
}
#body {
   padding-bottom:15%;   /* Height of the footer */
}
#footer {
   position:absolute;
   bottom:4%;
   width:100%;
   height:14%;   /* Height of the footer */
}
#footer div.left {
 float: left; 
  margin-left:5%;
}
#footer div.right {
 float: right; 
 margin-right:5%;
 margin-top:3%;
}
.margin-top-bottom {
 margin-top: 2%;
 margin-bottom: 1%;
}
#disclaimer {
  font-size:75%;
}
.popover {
	width: 20%;
}

.popover.top {
    margin-left: -8%;
}

.popover.top .arrow {
    margin-left: +35%;
}

@media only screen and (max-width: 450px) {
  body {
    font-size: 40%;
    background-size: 112% auto;
  }
  #disclaimer {
    font-size:50%;
  }
  .popover {
	width: 40%;
  }
  #footer {
   bottom:12%;
  }
}

</style>
<% content_for :title, "Title for specific page" %>
<div id="container">
    <div id="header">
        <div class="align-right"><%= @showPhraseCount %> frases!</div>
    </div>
    <div id="body">
        <h3 class="margin-bottom:-15px;">Ahora que el Papa es argentino,</h3>
        <h1><%= @showText %></h1>
        <%= form_tag :controller => :phrases, :action => :create, :method => :post, :align => :center  do %>
            <div class="align-center margin-top-bottom">
                <%= text_field_tag 'text', '', :class => "input-xxlarge", :placeholder => "Sugerí tu frase acá" %>
            </div>
            <div class="align-center">
                <%= submit_tag "      Sugerir      ", class:"btn btn-success"  %>
                <%= submit_tag "      Otra frase      ", class:"btn"  %>
            </div>
        <% end %>
    </div>
    <div id="footer">
        <div class="left">
            <p id="sobreMi">Sobre mí</p>
            <div>
                <a href="http://www.linkedin.com/in/damianferrai" target="_blank"><img src="assets/social/linkedin.png" alt="Linkedin" title="Linkedin"></a>
                <a href="http://www.facebook.com/damian.ferrai/" target="_blank"><img src="assets/social/facebook.png" alt="Facebook" title="Facebook"></a>

            </div>
        </div>
        <div class="right">
            <%= link_to('?', '#', :class => "btn popover-with-html", :title => "Sobre Frases Papales", :"data-placement"=>"top") %>
        </div>
        <div id="popover_content_wrapper" style="display: none;">
            <div id="disclaimer">Este sitio fue realizado utilizando Ruby on Rails con fines de aprendizaje. Las frases que se muestran fueron recopiladas de distintos medios y no expresan la visión del autor. Todos los derechos reservados.
            </div>
        </div>
    </div>
</div>

frasespapales_rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Frases Papales</title>
  <link rel="image_src" href="assets/vatican_flag.jpg" / >
  <link rel="image_src" href="assets/vatican_old.jpg" / >
  <meta name="description" content="Cualquier frase puede ir después de "Ahora que el Papa es argentino". O no?" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script>
$(function () {
     $('.popover-with-html').popover({ 
        html : true,
        offset:500,
        content: function() {
            return $('#popover_content_wrapper').html();
        }
     });
  });
  

  var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-39404859-1']);
_gaq.push(['_trackPageview']);

(function() {
 var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
 ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
 var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 })();
 
   </script>
</head>
<body>

<%= yield %>

</body>
</html>

frasespapales_rails/app/views/phrases/_form.html.erb
<%= form_for(@phrase) do |f| %>
  <% if @phrase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phrase.errors.count, "error") %> prohibited this phrase from being saved:</h2>

      <ul>
      <% @phrase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.number_field :votes %>
  </div>
  <div class="field">
    <%= f.label :created_date %><br />
    <%= f.date_select :created_date %>
  </div>
  <div class="field">
    <%= f.label :origin %><br />
    <%= f.text_field :origin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

frasespapales_rails/app/views/phrases/edit.html.erb
<h1>Editing phrase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phrase %> |
<%= link_to 'Back', phrases_path %>

frasespapales_rails/app/views/phrases/index.html.erb
<h1>Listing phrases</h1>

<table>
  <tr>
    <th>Text</th>
    <th>Votes</th>
    <th>Created date</th>
    <th>Origin</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phrases.each do |phrase| %>
  <tr>
    <td><%= phrase.text %></td>
    <td><%= phrase.votes %></td>
    <td><%= phrase.created_date %></td>
    <td><%= phrase.origin %></td>
    <td><%= link_to 'Show', phrase %></td>
    <td><%= link_to 'Edit', edit_phrase_path(phrase) %></td>
    <td><%= link_to 'Destroy', phrase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phrase', new_phrase_path %>

frasespapales_rails/app/views/phrases/new.html.erb
<h1>New phrase</h1>

<%= render 'form' %>

<%= link_to 'Back', phrases_path %>

frasespapales_rails/app/views/phrases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @phrase.text %>
</p>

<p>
  <b>Votes:</b>
  <%= @phrase.votes %>
</p>

<p>
  <b>Created date:</b>
  <%= @phrase.created_date %>
</p>

<p>
  <b>Origin:</b>
  <%= @phrase.origin %>
</p>

<p>
  <b>Approved:</b>
  <%= @phrase.approved %>
</p>


<%= link_to 'Edit', edit_phrase_path(@phrase) %> |
<%= link_to 'Back', phrases_path %>